version: '2'
services:
  extractor:
    build:
      context: .
      args:
        PYPI_USER: ${PYPI_USER}
        PYPI_PASSWORD: ${PYPI_PASSWORD}
    volumes:
      - ./src:/code/src
      - ./config/config.json:/data/config.json
      - ./output:/data/out/tables/
